# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HackathonAppProject20181130' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HackathonAppProject20181130

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'HackathonAppProject20181130Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
